# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'droidsec.ui'
#
# Created: Wed Nov 18 00:30:08 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1280, 800)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 1261, 741))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.loadedAPK_label = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadedAPK_label.sizePolicy().hasHeightForWidth())
        self.loadedAPK_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.loadedAPK_label.setFont(font)
        self.loadedAPK_label.setObjectName(_fromUtf8("loadedAPK_label"))
        self.verticalLayout_2.addWidget(self.loadedAPK_label)
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_3.sizePolicy().hasHeightForWidth())
        self.tab_3.setSizePolicy(sizePolicy)
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 0, 1231, 671))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.logArea = QtGui.QTextBrowser(self.groupBox_2)
        self.logArea.setEnabled(True)
        self.logArea.setGeometry(QtCore.QRect(10, 30, 1211, 261))
        self.logArea.setAutoFillBackground(False)
        self.logArea.setStyleSheet(_fromUtf8("background-color:black;"))
        self.logArea.setObjectName(_fromUtf8("logArea"))
        self.clearLogBtn = QtGui.QPushButton(self.groupBox_2)
        self.clearLogBtn.setGeometry(QtCore.QRect(10, 290, 110, 32))
        self.clearLogBtn.setObjectName(_fromUtf8("clearLogBtn"))
        self.saveLogBtn = QtGui.QPushButton(self.groupBox_2)
        self.saveLogBtn.setGeometry(QtCore.QRect(130, 290, 110, 32))
        self.saveLogBtn.setObjectName(_fromUtf8("saveLogBtn"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 319, 1211, 341))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.appInfoTable = QtGui.QTableWidget(self.groupBox_4)
        self.appInfoTable.setGeometry(QtCore.QRect(10, 30, 581, 301))
        self.appInfoTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.appInfoTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.appInfoTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.appInfoTable.setObjectName(_fromUtf8("appInfoTable"))
        self.appInfoTable.setColumnCount(3)
        self.appInfoTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.appInfoTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.appInfoTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.appInfoTable.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.permsTable = QtGui.QTableWidget(self.groupBox_3)
        self.permsTable.setGeometry(QtCore.QRect(10, 30, 581, 301))
        self.permsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.permsTable.setShowGrid(True)
        self.permsTable.setObjectName(_fromUtf8("permsTable"))
        self.permsTable.setColumnCount(1)
        self.permsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.permsTable.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox = QtGui.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 281, 591))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tree_area = QtGui.QWidget(self.groupBox)
        self.tree_area.setGeometry(QtCore.QRect(10, 30, 251, 551))
        self.tree_area.setObjectName(_fromUtf8("tree_area"))
        self.sourceTextWidget = QtGui.QWidget(self.tab_4)
        self.sourceTextWidget.setGeometry(QtCore.QRect(300, 0, 911, 621))
        self.sourceTextWidget.setObjectName(_fromUtf8("sourceTextWidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 294, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.saveJavaSources = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.saveJavaSources.setObjectName(_fromUtf8("saveJavaSources"))
        self.horizontalLayout.addWidget(self.saveJavaSources)
        self.showManifestBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.showManifestBtn.setObjectName(_fromUtf8("showManifestBtn"))
        self.horizontalLayout.addWidget(self.showManifestBtn)
        self.showStringsBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.showStringsBtn.setObjectName(_fromUtf8("showStringsBtn"))
        self.horizontalLayout.addWidget(self.showStringsBtn)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 281, 631))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.resourceFileTable = QtGui.QTableWidget(self.groupBox_5)
        self.resourceFileTable.setGeometry(QtCore.QRect(10, 30, 256, 591))
        self.resourceFileTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.resourceFileTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.resourceFileTable.setAutoScroll(True)
        self.resourceFileTable.setObjectName(_fromUtf8("resourceFileTable"))
        self.resourceFileTable.setColumnCount(1)
        self.resourceFileTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.resourceFileTable.setHorizontalHeaderItem(0, item)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(290, 0, 921, 511))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.graphicview = QtGui.QLabel(self.groupBox_6)
        self.graphicview.setGeometry(QtCore.QRect(10, 30, 901, 461))
        self.graphicview.setObjectName(_fromUtf8("graphicview"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(290, 500, 921, 121))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.fileResourceInfo = QtGui.QTextEdit(self.groupBox_7)
        self.fileResourceInfo.setGeometry(QtCore.QRect(10, 30, 901, 78))
        self.fileResourceInfo.setObjectName(_fromUtf8("fileResourceInfo"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ARES", None))
        self.loadedAPK_label.setText(_translate("MainWindow", "No APK Loaded", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Log", None))
        self.clearLogBtn.setText(_translate("MainWindow", "Clear", None))
        self.saveLogBtn.setText(_translate("MainWindow", "Save ...", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Application Info", None))
        item = self.appInfoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Application Variable", None))
        item = self.appInfoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        item = self.appInfoTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Action", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Permissions", None))
        item = self.permsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Uses permissions", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "APK", None))
        self.groupBox.setTitle(_translate("MainWindow", "Sources", None))
        self.saveJavaSources.setText(_translate("MainWindow", "Save ...", None))
        self.showManifestBtn.setText(_translate("MainWindow", "Manifest ...", None))
        self.showStringsBtn.setText(_translate("MainWindow", "Strings ...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Sources", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Files from APK", None))
        item = self.resourceFileTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Filename", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Viewer", None))
        self.graphicview.setText(_translate("MainWindow", "Graphic", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "File Info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Resources", None))

